name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: |
        Write-Host "Restoring NuGet packages..."
        nuget restore FluentBuilderPattern.sln
        if ($LASTEXITCODE -ne 0) {
          Write-Error "NuGet restore failed"
          exit 1
        }
      shell: powershell

    - name: Build solution
      run: |
        Write-Host "Building solution..."
        msbuild FluentBuilderPattern.sln /p:Configuration=Release /p:Platform=x64 /p:WarningLevel=4 /verbosity:minimal
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Build failed"
          exit 1
        }
      shell: powershell

    - name: Verify test executable exists
      run: |
        $testExe = ".\UnitTests\out\Release-x64\UnitTests.exe"
        if (Test-Path $testExe) {
          Write-Host "Test executable found at: $testExe"
          Write-Host "File size: $((Get-Item $testExe).Length) bytes"
        } else {
          Write-Error "Test executable not found at $testExe"
          Write-Host "Contents of UnitTests\out directory:"
          if (Test-Path ".\UnitTests\out") {
            Get-ChildItem -Recurse ".\UnitTests\out"
          }
          exit 1
        }
      shell: powershell

    - name: Run unit tests
      run: |
        $testExe = ".\UnitTests\out\Release-x64\UnitTests.exe"
        Write-Host "Running tests..."
        & $testExe --gtest_output=xml:test_results.xml
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Tests failed with exit code $LASTEXITCODE"
          exit 1
        }
        Write-Host "All tests passed!"
      shell: powershell

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test_results.xml